@hostname = rest.dev.yii2
@error401 = error401
@error500 = error500
@errorexception = errorexception
@errormodel = errormodel
@contentType = application/json


POST https://{{hostname}}/test
Content-Type: {{contentType}}

POST https://{{hostname}}/test/{{error401}}
Content-Type: {{contentType}}

###
POST https://{{hostname}}/test/{{error500}}
Content-Type: {{contentType}}

###
POST https://{{hostname}}/test/{{errormodel}}
Content-Type: {{contentType}}

###
POST https://{{hostname}}/test/{{errorexception}}
Content-Type: {{contentType}}
